In [1]:
import numpy as np

In [2]:
a = np.array([2,3,4])

In [3]:
a

array([2, 3, 4])

In [4]:
a.dtype

dtype('int64')

In [5]:
b = np.array([1.2,3.5,5.1])

In [6]:
b.dtype

dtype('float64')

array 만들때, () 안에 [] 을 넣는걸 조심해라.

In [24]:
b = np.array([2,3,4], 'int32')

In [25]:
b

array([2, 3, 4], dtype=int32)

In [26]:
c = np.array([[1,2], [3,4]], dtype=complex)

In [27]:
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [28]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [30]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [32]:
np.empty((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

Numpy는 몃몃의 배열을 창조해주는 function들을 제공합니다. 
뿐만이라라, zeros 로 zeros가 가득찬 배열을 제공한다.

만약 일련의 숫자들을 생성하기 위해서, Numpy는 range와 유사한 함수를 제공합니다.

In [38]:
np.arange(10, 30, 5)  # 10 부터 30까지 5의 간격으로 30까지는 안함.

array([10, 15, 20, 25])

In [34]:
np.arange(0, 2, 0.3)

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [39]:
from numpy import pi

In [44]:
np.linspace(0, 2, 9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [47]:
x= np.linspace(0, 2*pi, 100)

In [46]:
f = np.sin(x)

## Printing Arrays

In [50]:
a = np.arange(6)

In [51]:
print(a)

[0 1 2 3 4 5]


In [52]:
b = np.arange(12).reshape(4,3)

In [53]:
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [54]:
c = np.arange(24).reshape(2,3,4)

In [55]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [57]:
print(np.arange(10000))

[   0    1    2 ..., 9997 9998 9999]


In [ ]:
np.set_printoptions(threshold= 10)