In [3]:
import numpy as np
# https://docs.scipy.org/doc/numpy/user/quickstart.html

In [2]:
a = np.array([20,30,40,50])

In [3]:
b = np.arange(4)

In [4]:
b

array([0, 1, 2, 3])

In [5]:
a

array([20, 30, 40, 50])

In [6]:
b**2

array([0, 1, 4, 9])

In [7]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [8]:
a < 35

array([ True,  True, False, False], dtype=bool)

다른 매트릭스 랭귀지와는 다르게, product operator * 는 각 배열읠 요소별로 수행된다.

In [9]:
A = np.array([[1,1],[0,1]])

In [10]:
B = np.array([[2,0], [3,4]])

In [14]:
# element-wise product
A * B

array([[2, 0],
       [0, 4]])

In [13]:
# matrix product
A @ B

array([[5, 4],
       [3, 4]])

In [15]:
A.dot(B)

array([[5, 4],
       [3, 4]])

일부 연산자들  `+=` 그리고 `*=` 는 새로운 배열을 생성하기 보다는 기존에 있던 배열을 수정하는 행동으로 사용된다.

In [16]:
a = np.ones((2,3), dtype=int)

In [18]:
b = np.random.random((2,3))

In [19]:
a *= 3

In [20]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [30]:
a += a # 스스로의 배열에만 영향을 미친다.

In [31]:
a    # 변화되지 않았음.

array([[12, 12, 12],
       [12, 12, 12]])

In [23]:
a += b

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [32]:
a = np.ones(3, dtype=np.int32)

In [35]:
from numpy import pi
b = np.linspace(0, pi, 3)

In [36]:
b.dtype.name

'float64'

In [37]:
c = a+ b

In [38]:
c

array([ 1.        ,  2.57079633,  4.14159265])

In [39]:
c.dtype.name

'float64'

In [40]:
d = np.exp(c*1j)

In [41]:
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [42]:
d.dtype.name

'complex128'

In [43]:
a = np.random.random((2,3))

In [44]:
a

array([[ 0.4159594 ,  0.62202294,  0.23350428],
       [ 0.8725842 ,  0.8498893 ,  0.46176669]])

In [45]:
a.sum()

3.4557268169484687

In [46]:
a.min()

0.23350428284424307

In [47]:
a.max()

0.87258420488053579

기본적으로 모든 연산자들은 모양에 상관없이 숫자목록인 것처럼 배열에 적용된다.

In [50]:
b = np.arange(12).reshape(3, 4)

In [51]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
# 각각의 column의 합으로 표현한다.
b.sum(axis=0) 

# 0은 축의 모양을 뜻함 -> column
# 1은 row

array([ 6, 22, 38])

In [53]:
# 각각의 row에서 최소
b.min(axis=1) 

array([0, 4, 8])

In [56]:
# 각 행에 누적을 계산 때 활용.
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

# Univarsal Functions

Numpy는 sin, cos, exp 와 같은 수학 함수들을 제공합니다. 이러한 것을 우리는 universal functions 즉, ufunc 이라고 부릅니다. Numpy 안에서 이러한 Functions 는 배열안에서 각각의 요소별로 동작하게 됩니다. 아래를 보시죠

In [58]:
B = np.arange(3)

In [59]:
B

array([0, 1, 2])

In [60]:
np.exp(B)

array([ 1.        ,  2.71828183,  7.3890561 ])

In [65]:
np.sqrt(B)

array([ 0.        ,  1.        ,  1.41421356])

In [62]:
C = np.array([2., -1. , 4.])

In [63]:
np.add(B, C)

array([ 2.,  0.,  6.])

# Indexing, Slicing and Iterating

In [90]:
a = np.arange(10) ** 3
# 각각의 요소를 3번씩 곱한다.

In [92]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [68]:
a[2]

8

In [69]:
a[2:5]

array([ 8, 27, 64])

In [96]:
# 0:6:2 와 동일 시작부터 6번포지션까지만 
# 예외적으로 매 2번째 요소에 -1000을 넣겠다.
a[0:6:2] = -1000

In [87]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729])

In [88]:
# 뒤집기
a[ : :-1]  

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1, -1000])

In [94]:
a[ ::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [97]:
for i in a:
    print(i**(1/3.))

nan
1.0
nan
3.0
nan
5.0
6.0
7.0
8.0
9.0


/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


다차원 배열이 각 축마다 하나의 인덱스를 가질 수있다. 이러한 인덱스들은 컴마에 의해 튜플로 주어지게 된다.

In [15]:
def f(x,y):
    return 10*x+y

In [16]:
b = np.fromfunction(f, (5,4), dtype=int)

In [100]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [101]:
b[2,3]

23

In [102]:
#두번째 컬럼에서 각각의 row들
b[0:5, 1] 

array([ 1, 11, 21, 31, 41])

In [114]:
b[:,1]

array([ 1, 11, 21, 31, 41])

In [115]:
b[1:3, : ]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [116]:
# the last row. Equivalent to b[-1,:]
b[-1] 

array([40, 41, 42, 43])

b[i, ...]. 이런 표현도 있음. dots는 가능한 축들을 축약해서 쓸 수 있다.

- x[1,2,....] 는 x[1,2,:,:,:],
- x[...,3] 는 x[:,:,:,:,3]
- x[4,...,5,:] 는 x[4,:,:,5,:]

In [9]:
c = np.array([[[0, 1, 2],
               [10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])


In [10]:
c.shape

(2, 2, 3)

In [11]:
c[1, ...] # c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [12]:
c[..., 2]  # c[:,:,2]


array([[  2,  13],
       [102, 113]])

In [17]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [18]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


# Shap Manipulation

In [31]:
a= np.floor(10*np.random.random((3,4)))

In [32]:
a

array([[ 7.,  7.,  9.,  1.],
       [ 0.,  8.,  1.,  0.],
       [ 2.,  4.,  0.,  3.]])

In [33]:
a.ravel() # flattened

array([ 7.,  7.,  9.,  1.,  0.,  8.,  1.,  0.,  2.,  4.,  0.,  3.])

In [34]:
a.reshape(6,2) # returns the array with new modified shape

array([[ 7.,  7.],
       [ 9.,  1.],
       [ 0.,  8.],
       [ 1.,  0.],
       [ 2.,  4.],
       [ 0.,  3.]])

In [35]:
a.T # 가로 세로 변형된 형태 제공

array([[ 7.,  0.,  2.],
       [ 7.,  8.,  4.],
       [ 9.,  1.,  0.],
       [ 1.,  0.,  3.]])

In [36]:
a.T.shape

(4, 3)

In [37]:
a.shape

(3, 4)

# Stacking together different arrays

In [38]:
a = np.floor(10*np.random.random((2,2)))

In [39]:
a

array([[ 2.,  3.],
       [ 4.,  8.]])

In [40]:
b = np.floor(10*np.random.random((2,2)))

In [41]:
b

array([[ 4.,  7.],
       [ 2.,  2.]])

In [42]:
np.vstack((a,b))

array([[ 2.,  3.],
       [ 4.,  8.],
       [ 4.,  7.],
       [ 2.,  2.]])

In [44]:
np.hstack((a,b))

array([[ 2.,  3.,  4.,  7.],
       [ 4.,  8.,  2.,  2.]])

In [45]:
from numpy import newaxis

In [46]:
np.column_stack((a, b))

array([[ 2.,  3.,  4.,  7.],
       [ 4.,  8.,  2.,  2.]])

In [48]:
a= np.array([4.,2.])

In [49]:
b = np.array([3.,8.])

In [50]:
np.column_stack((a,b)) # 2D 배열로 변환되어 리턴함.

array([[ 4.,  3.],
       [ 2.,  8.]])

In [51]:
np.hstack((a,b))

array([ 4.,  2.,  3.,  8.])

In [52]:
a[:, newaxis] # 이건 2D 열 벡터를 가질수 있도록 허락한다.

array([[ 4.],
       [ 2.]])

In [56]:
np.column_stack((a[:, newaxis], b[:,newaxis]))

array([[ 4.,  3.],
       [ 2.,  8.]])

In [58]:
np.hstack((a[:, newaxis], b[:, newaxis]))


array([[ 4.,  3.],
       [ 2.,  8.]])

Node

In [59]:
np.r_[1:4, 0, 4]

array([1, 2, 3, 0, 4])

# 하나의 배열을 여러 배열로 쪼개기

In [61]:
a = np.floor(10*np.random.random((2,12)))

In [62]:
a

array([[ 8.,  6.,  1.,  2.,  5.,  8.,  8.,  1.,  1.,  6.,  3.,  5.],
       [ 4.,  2.,  7.,  8.,  4.,  6.,  7.,  9.,  3.,  4.,  5.,  0.]])

In [63]:
np.hsplit(a, 3)  # 배열을 3개로 나눈다.

[array([[ 8.,  6.,  1.,  2.],
        [ 4.,  2.,  7.,  8.]]), array([[ 5.,  8.,  8.,  1.],
        [ 4.,  6.,  7.,  9.]]), array([[ 1.,  6.,  3.,  5.],
        [ 3.,  4.,  5.,  0.]])]

In [65]:
np.hsplit(a, (3, 4))

[array([[ 8.,  6.,  1.],
        [ 4.,  2.,  7.]]), array([[ 2.],
        [ 8.]]), array([[ 5.,  8.,  8.,  1.,  1.,  6.,  3.,  5.],
        [ 4.,  6.,  7.,  9.,  3.,  4.,  5.,  0.]])]

# Copy and Views

In [96]:
a = np.arange(12)

In [120]:
b = a # 어떤 새로운 오브젝트가 생성된것이 아니다. 포인터로 연결된 것으로  예상됨

In [121]:
b is a # a and b 두개는 같은 이름을 가진 ndarray object이다.

True

In [122]:
b.shape = 3, 4

In [123]:
a. shape

(3, 4)

In [124]:
def f(x):
    print(id(x))

In [125]:
id(a) # id는 유니크한 UUID이다.

4494863536

In [126]:
f(a)

4494863536


## View or 얖은 복사

In [127]:
c = a.view()

In [154]:
c is a

False

In [129]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [130]:
c.base is a # C 는 데이터 a의 뷰이다. 데이터는 공유한다.

True

In [131]:
c.flags.owndata

False

In [132]:
c.shape

(3, 4)

In [133]:
c.shape = 2,6 # a의 모양은 변하지 않는다.

In [134]:
c[0, 4] = 1234


In [135]:
c

array([[   0,    1,    2,    3, 1234,    5],
       [   6,    7,    8,    9,   10,   11]])

In [140]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

슬라이싱하는 것 배열을 뷰에 의해 리턴 된 것을

In [150]:
a[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [151]:
s = a[:, 1:3]  # s = a[:,1:3] 지금 View를 리턴한 것!!

In [152]:
s

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [153]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

# 깊은 복사

In [155]:
d = a.copy() # 새로운 객체에 새로운 데이터가 생성됨

In [156]:
d is a

False

In [157]:
d.base is a # 얖은 복사와 달리 데이터도 공유하지 않음.

False

In [158]:
d[0, 0] = 9999

In [159]:
a # 변하지 않음을 알 수 있음.

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

방송은 보편적 인 기능이 정확히 같은 모양을 갖지 않는 입력을 의미있는 방식으로 처리 할 수있게합니다.

브로드 캐스팅의 첫 번째 규칙은 모든 입력 배열의 차원 수가 같지 않으면 모든 배열의 차원 수가 같을 때까지 더 작은 배열의 모양에 "1"이 반복적으로 추가된다는 것입니다.

브로드 캐스팅의 두 번째 규칙은 특정 차원을 따라 1 크기의 배열이 해당 차원을 따라 가장 큰 형태의 배열 크기를 갖는 것처럼 작동하도록합니다. 배열 요소의 값은 "브로드 캐스트"배열의 차원을 따라 동일하다고 가정합니다.

브로드 캐스팅 규칙을 적용한 후에는 모든 배열의 크기가 일치해야합니다. 자세한 내용은 방송에서 찾을 수 있습니다.

## Fancy indexing and index tricks

In [210]:
a = np.arange(12) ** 2

In [211]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [212]:
i = np.array([1, 1, 3, 8, 5])


In [213]:
a[i] # i 위치에 있는 index로 위치를 반납.

array([ 1,  1,  9, 64, 25])

In [214]:
j = np.array([[3, 4], [9, 7]])

In [215]:
a[j] # 이차원도 아래와 같이 같은 모양으로 나타냄.

array([[ 9, 16],
       [81, 49]])

```
>>> palette = np.array( [ [0,0,0],                # black
...                       [255,0,0],              # red
...                       [0,255,0],              # green
...                       [0,0,255],              # blue
...                       [255,255,255] ] )       # white
>>> image = np.array( [ [ 0, 1, 2, 0 ],           # each value corresponds to a color in the palette
...                     [ 0, 3, 4, 0 ]  ] )
>>> palette[image]                            # the (2,4,3) color image
array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],
       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])
```

In [218]:
a = np.arange(12).reshape(3,4)

In [219]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [220]:
i = np.array([[0, 1], 
              [1, 2]])


In [221]:
j = np.array([[2, 1], 
              [3, 3]])


In [222]:
i

array([[0, 1],
       [1, 2]])

In [223]:
j

array([[2, 1],
       [3, 3]])

In [224]:
a[i,j]

array([[ 2,  5],
       [ 7, 11]])

In [225]:
a[i, 2]


array([[ 2,  6],
       [ 6, 10]])

In [226]:
a[:,j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [234]:
l = [i,j]

In [235]:
a[l]

array([[ 2,  5],
       [ 7, 11]])

In [236]:
s = np.array([i,j])

In [237]:
a[s]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [238]:
a[tuple(s)]

array([[ 2,  5],
       [ 7, 11]])

In [239]:
time = np.linspace(20, 145,5)

In [240]:
time

array([  20.  ,   51.25,   82.5 ,  113.75,  145.  ])

In [243]:
data = np.sin(np.arange(20)).reshape(5,4)

In [244]:
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [247]:
ind = data.argmax(axis=0) # 각 시리즈의 최대값의 인덱스

In [248]:
ind

array([2, 0, 3, 1])

In [253]:
time_max = time[ind]

In [254]:
time_max

array([  82.5 ,   20.  ,  113.75,   51.25])

In [255]:
# => data[ind[0],0], data[ind[1],1]...
data_max = data[ind, range(data.shape[1])]

In [256]:
data_max

array([ 0.98935825,  0.84147098,  0.99060736,  0.6569866 ])

In [257]:
np.all(data_max == data.max(axis=0))

True

그러나 인덱스 목록에 반복이 포함되어 있으면 마지막 값 뒤에두고 여러 번 할당됩니다.

In [269]:
a= np.arange(5)

In [278]:
a[[0,0,2]] = [1,2,3]

In [279]:
a

array([2, 1, 3, 3, 4])

# Indexing with Boolean Arrays

In [280]:
a = np.arange(12).reshape(3,4)

In [281]:
b = a > 4

In [282]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [283]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [284]:
a[b] = 0

In [285]:
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])