In [1]:
import numpy as np

In [2]:
a = np.array([20,30,40,50])

In [3]:
b = np.arange(4)

In [4]:
b

array([0, 1, 2, 3])

In [5]:
a

array([20, 30, 40, 50])

In [6]:
b**2

array([0, 1, 4, 9])

In [7]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [8]:
a < 35

array([ True,  True, False, False], dtype=bool)

다른 매트릭스 랭귀지와는 다르게, product operator * 는 각 배열읠 요소별로 수행된다.

In [9]:
A = np.array([[1,1],[0,1]])

In [10]:
B = np.array([[2,0], [3,4]])

In [14]:
# element-wise product
A * B

array([[2, 0],
       [0, 4]])

In [13]:
# matrix product
A @ B

array([[5, 4],
       [3, 4]])

In [15]:
A.dot(B)

array([[5, 4],
       [3, 4]])

일부 연산자들  `+=` 그리고 `*=` 는 새로운 배열을 생성하기 보다는 기존에 있던 배열을 수정하는 행동으로 사용된다.

In [16]:
a = np.ones((2,3), dtype=int)

In [18]:
b = np.random.random((2,3))

In [19]:
a *= 3

In [20]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [30]:
a += a # 스스로의 배열에만 영향을 미친다.

In [31]:
a    # 변화되지 않았음.

array([[12, 12, 12],
       [12, 12, 12]])

In [23]:
a += b

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [32]:
a = np.ones(3, dtype=np.int32)

In [35]:
from numpy import pi
b = np.linspace(0, pi, 3)

In [36]:
b.dtype.name

'float64'

In [37]:
c = a+ b

In [38]:
c

array([ 1.        ,  2.57079633,  4.14159265])

In [39]:
c.dtype.name

'float64'

In [40]:
d = np.exp(c*1j)

In [41]:
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [42]:
d.dtype.name

'complex128'

In [43]:
a = np.random.random((2,3))

In [44]:
a

array([[ 0.4159594 ,  0.62202294,  0.23350428],
       [ 0.8725842 ,  0.8498893 ,  0.46176669]])

In [45]:
a.sum()

3.4557268169484687

In [46]:
a.min()

0.23350428284424307

In [47]:
a.max()

0.87258420488053579

기본적으로 모든 연산자들은 모양에 상관없이 숫자목록인 것처럼 배열에 적용된다.

In [50]:
b = np.arange(12).reshape(3, 4)

In [51]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
# 각각의 column의 합으로 표현한다.
b.sum(axis=0) 

# 0은 축의 모양을 뜻함 -> column
# 1은 row

array([ 6, 22, 38])

In [53]:
# 각각의 row에서 최소
b.min(axis=1) 

array([0, 4, 8])

In [56]:
# 각 행에 누적을 계산 때 활용.
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

# Univarsal Functions

Numpy는 sin, cos, exp 와 같은 수학 함수들을 제공합니다. 이러한 것을 우리는 universal functions 즉, ufunc 이라고 부릅니다. Numpy 안에서 이러한 Functions 는 배열안에서 각각의 요소별로 동작하게 됩니다. 아래를 보시죠

In [58]:
B = np.arange(3)

In [59]:
B

array([0, 1, 2])

In [60]:
np.exp(B)

array([ 1.        ,  2.71828183,  7.3890561 ])

In [65]:
np.sqrt(B)

array([ 0.        ,  1.        ,  1.41421356])

In [62]:
C = np.array([2., -1. , 4.])

In [63]:
np.add(B, C)

array([ 2.,  0.,  6.])

# Indexing, Slicing and Iterating

In [90]:
a = np.arange(10) ** 3
# 각각의 요소를 3번씩 곱한다.

In [92]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [68]:
a[2]

8

In [69]:
a[2:5]

array([ 8, 27, 64])

In [96]:
# 0:6:2 와 동일 시작부터 6번포지션까지만 
# 예외적으로 매 2번째 요소에 -1000을 넣겠다.
a[0:6:2] = -1000

In [87]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729])

In [88]:
# 뒤집기
a[ : :-1]  

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1, -1000])

In [94]:
a[ ::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [97]:
for i in a:
    print(i**(1/3.))

nan
1.0
nan
3.0
nan
5.0
6.0
7.0
8.0
9.0


/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


다차원 배열이 각 축마다 하나의 인덱스를 가질 수있다. 이러한 인덱스들은 컴마에 의해 튜플로 주어지게 된다.

In [98]:
def f(x,y):
    return 10*x+y

In [99]:
b = np.fromfunction(f, (5,4), dtype=int)

In [100]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [101]:
b[2,3]

23

In [102]:
#두번째 컬럼에서 각각의 row들
b[0:5, 1] 

array([ 1, 11, 21, 31, 41])

In [114]:
b[:,1]

array([ 1, 11, 21, 31, 41])

In [115]:
b[1:3, : ]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [116]:
# the last row. Equivalent to b[-1,:]
b[-1] 

array([40, 41, 42, 43])