# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

1.14.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
blas_opt_info:
    extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_clapack_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_opt_info:
    extra_compile_args = ['-msse3']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [4]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [8]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [10]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.94999866 0.73617707 0.64764482]
  [0.02672565 0.53711161 0.8875131 ]
  [0.09973913 0.88156772 0.78094543]]

 [[0.90960336 0.1034352  0.92605165]
  [0.54578374 0.36906284 0.47639372]
  [0.43248216 0.85199028 0.36639323]]

 [[0.1589847  0.60612707 0.83436405]
  [0.64195496 0.19856817 0.03121485]
  [0.8820021  0.27883711 0.25618875]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

6.730566362511681e-05 0.9979174656993762


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5317977610726775


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [19]:
a = np.array([1,2,3,4,5,6]).reshape([3,2])
b = np.diag(a)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
np.diag(b)

array([[1, 0],
       [0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
Z = np.arange(0,25,1).reshape([-1,5])
Z

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
Z[::2,::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

In [23]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [24]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [25]:
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [26]:
Z = np.random.random((5,5))
print(Z)
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[0.61489934 0.50813455 0.69132412 0.37130767 0.43849817]
 [0.20050796 0.30186188 0.76719139 0.25360282 0.31540599]
 [0.57302319 0.02181049 0.95942427 0.71207969 0.7671274 ]
 [0.41171126 0.37415679 0.51976274 0.18427104 0.67279248]
 [0.72885758 0.66832948 0.53893162 0.86466544 0.18501638]]
[[ 0.46208833  0.0099387   0.78574777 -0.56952406 -0.28497181]
 [-1.29286196 -0.86362745  1.10704618 -1.06800488 -0.80626804]
 [ 0.28474254 -2.04964696  1.92115372  0.87364777  1.10677516]
 [-0.39841457 -0.55745801  0.05918419 -1.36162542  0.70726617]
 [ 0.94470223  0.68836533  0.14036451  1.51984944 -1.35846889]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [27]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [28]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [29]:
# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)

In [30]:
# Author: Jake VanderPlas

print(sum(range(5),-1)) # sum(iterable, start)
from numpy import *
print(sum(range(5),-1)) # numpy.sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>)

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

In [31]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: Integers to negative integer powers are not allowed.

#### 28. What are the result of the following expressions?

In [45]:
a = np.array([5])
b = a // 10 # //는 소수를 버리는 절대값
b

array([0])

In [46]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/anaconda3/envs/new_env/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/anaconda3/envs/new_env/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [47]:
# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)), Z)) 
# numpy.copysign(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'copysign'>
# 앞서 계산된 것에 부호를 변경해준다.

[ 7.50374043  8.21008614 -3.03593115  1.72504436  0.40462775  2.40867161
  0.82995939 -2.60414928 -8.53157798  8.39181861]
[ 8.  9. -4.  2.  1.  3.  1. -3. -9.  9.]


#### 30. How to find common values between two arrays? (★☆☆)

In [48]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))
# Find the intersection of two arrays.

[1 5 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [49]:
# Suicide mode on
# defaults = np.seterr(all="ignore")

# Back to sanity
_ = np.seterr(**defaults)
Z = np.ones(1) / 0
Z
# An equivalent way, with a context manager:

# with np.errstate(divide='ignore'):
#     Z = np.ones(1) / 0
#     print(Z)

NameError: name 'defaults' is not defined

#### 32. Is the following expressions true? (★☆☆)

In [50]:
np.sqrt(-1) == np.emath.sqrt(-1)
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

nan
1j


/anaconda3/envs/new_env/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.
/anaconda3/envs/new_env/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [51]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print(yesterday)
today     = np.datetime64('today', 'D')
print(today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(tomorrow)

2019-01-23
2019-01-24
2019-01-25


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [52]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [53]:
import time
import numpy as np

In [54]:


a = ([1,2,3]) 

# np.empty_like(a)
# B = np.ones(3)*2
# [2,2,2]
start = time.time()
A = np.ones(10000000)
B = np.ones(10000000)*2
B = np.add(A,B)
end = time.time()
print((end-start))

start = time.time()
A = np.ones(10000000)
B = np.ones(10000000)*2
np.add(A,B, out=B)
end = time.time()
print("!!!!!!!!!!!!!!!!!!")
print((end-start))


# print(A)
# C = np.ones(3)*3
# D = np.ones(3)*10
# Q = np.array([1,2,3,4,5,6])
# np.empty_like(Q)
# print(B)
# print(np.divide(A,2,out=A))
# print(np.negative(A,out=A))
# print(np.multiply(A,B,out=A))

# https://stackoverflow.com/questions/20041570/numpy-ceil-and-floor-out-argument

0.1817929744720459
!!!!!!!!!!!!!!!!!!
0.0844731330871582


In [55]:
import random

In [56]:
Z2 = np.random.randint(0,10,10000000)

In [57]:
len(Z2)

10000000

In [58]:
import copy

In [59]:
Z3=copy.copy(Z2)
start = time.time()
print(id(Z3))
Z3 = sorted(Z3)
print(id(Z3))
end = time.time()
print((end-start))
print("!!!!!!!!!!!!!!!!!!")
print(id(Z2))
start = time.time()
Z2.sort()
end = time.time()
print(id(Z2))
print((end-start))

4563695216
4563604168
4.043483018875122
!!!!!!!!!!!!!!!!!!
4563696096
4563696096
0.291079044342041


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [60]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[7. 7. 2. 1. 3. 5. 4. 0. 1. 9.]
[7. 7. 2. 1. 3. 5. 4. 0. 1. 9.]
[7. 7. 2. 1. 3. 5. 4. 0. 1. 9.]
[7 7 2 1 3 5 4 0 1 9]
[7. 7. 2. 1. 3. 5. 4. 0. 1. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [61]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [62]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate() ,dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [63]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)
# Return evenly spaced numbers over a specified interval.

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [64]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.14943093 0.29003295 0.30231612 0.35892722 0.42829245 0.43950816
 0.45641588 0.87950074 0.93693753 0.95133362]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [65]:
# Author: Evgeni Burovski

Z = np.arange(10)
print(Z)
np.sum(Z)
# np.add.reduce(Z)
# https://stackoverflow.com/questions/16420097/what-is-the-difference-between-np-sum-and-np-add-reduce

[0 1 2 3 4 5 6 7 8 9]


45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [66]:
np.random.seed(1)
A = np.random.randint(0,2,5)
print(A)
B = np.random.randint(0,2,5)
print(B)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

[1 1 0 0 1]
[1 1 1 1 0]
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [67]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [68]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.20789248 0.52615268 0.68267673 0.71507097 0.87854443 0.78972779
 0.576058   0.82488549 1.0177255  1.11685655]
[1.11055409 0.85427034 0.66117595 0.28996514 0.03117888 0.55673373
 0.24618193 1.32826941 0.31305369 0.90220019]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [69]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.89460666 0.08504421 0.03905478 0.16983042 0.8781425  0.09834683
 0.42110763 0.         0.53316528 0.69187711]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [70]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)
# https://datascienceschool.net/view-notebook/17608f897087478bbeac096438c716f6/

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [71]:
# Author: Evgeni Burovski

X = np.arange(8)
print("X: {}".format(X))
Y = X + 0.5
print("Y: {}".format(X))
C = 1.0 / np.subtract.outer(X, Y)
print("C: {}".format(X))
print(C)
print(np.linalg.det(C))

X: [0 1 2 3 4 5 6 7]
Y: [0 1 2 3 4 5 6 7]
C: [0 1 2 3 4 5 6 7]
[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]
3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [72]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [73]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [74]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

32


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [75]:
Z = np.zeros(1, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)
position = (1,2)
color = (1,2,3)
abc = [(position, color)]
Z = abc
Z

[((0., 0.), (0., 0., 0.))]


[((1, 2), (1, 2, 3))]

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [76]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.67353192 0.31447894 0.40858111 0.69983669 0.58482431
  0.80959198 0.6850827  0.74118494 0.80521358]
 [0.67353192 0.         0.97057483 0.26506069 0.31395853 1.00053323
  0.67614112 0.07131694 0.52174245 0.84232026]
 [0.31447894 0.97057483 0.         0.70960913 0.93515392 0.46158383
  0.93467357 0.97196993 0.9148837  0.85442767]
 [0.40858111 0.26506069 0.70960913 0.         0.38464332 0.80016142
  0.65929152 0.28347672 0.52823435 0.76560371]
 [0.69983669 0.31395853 0.93515392 0.38464332 0.         0.82001351
  0.36755487 0.24569605 0.21213533 0.55359571]
 [0.58482431 1.00053323 0.46158383 0.80016142 0.82001351 0.
  0.64201084 0.96908355 0.69753231 0.48127795]
 [0.80959198 0.67614112 0.93467357 0.65929152 0.36755487 0.64201084
  0.         0.61092728 0.1554463  0.2177412 ]
 [0.6850827  0.07131694 0.97196993 0.28347672 0.24569605 0.96908355
  0.61092728 0.         0.45582019 0.78370604]
 [0.74118494 0.52174245 0.9148837  0.52823435 0.21213533 0.69753231
  0.1554463  0.45582

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [77]:
Z = np.arange(10, dtype=np.float32)
print('id -> {}'.format(id(Z)))
Z = Z.astype(np.int32, copy=False)
print('id -> {}'.format(id(Z)))
print(Z)

id -> 5308742512
id -> 4563106432
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)

In [78]:
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [79]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
    
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [80]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp( -( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [81]:
# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [82]:
# Author: Warren Weckesser

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.05197759 -0.25265375 -0.17448559 -0.16500422  0.61208896  0.04451116
  -0.27660466  0.41433281 -0.0279425  -0.12226462]
 [ 0.38197412  0.29323869  0.15956628  0.05133804 -0.56009902  0.21409385
   0.16279062 -0.14450005 -0.06795607 -0.49044645]
 [-0.20676608  0.15598991 -0.13714854  0.56364488  0.10935369 -0.22053155
   0.41144278 -0.14006513 -0.27854039 -0.25737958]
 [-0.31582485 -0.12156668 -0.38272255 -0.33476736  0.45298257  0.09855385
   0.36161485  0.14526175 -0.15351287  0.24998128]
 [-0.03226715  0.18180768 -0.38959767  0.13205451 -0.12819294  0.17355361
   0.20133161 -0.1573925   0.37019632 -0.35149346]]


#### 59. How to sort an array by the nth column? (★★☆)

In [83]:
# Author: Steve Tjoa

# Z = np.random.randint(0,10,(3,3))
Z = np.array([[3,2,4],[1,6,7],[8,4,2]])
print(Z)
# print(Z[:,1])

# n = 1
print(Z[Z[:,1].argsort()])

[[3 2 4]
 [1 6 7]
 [8 4 2]]
[[3 2 4]
 [8 4 2]
 [1 6 7]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [84]:
# Author: Warren Weckesser

Z = np.random.randint(0,3,(3,10))
print(Z)
print(~Z.any(axis=0))
print((~Z.any(axis=0)).any())

[[1 0 1 2 1 2 2 1 0 1]
 [2 2 0 0 0 2 0 1 0 2]
 [2 0 1 1 2 1 2 0 1 1]]
[False False False False False False False False False False]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [85]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5030759061202171


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [86]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [87]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [88]:
# Author: Brett Olsen

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
print(I)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[7 6 3 0 6 4 7 6 2 9 5 9 9 9 8 6 4 2 9 4]
[2. 1. 3. 2. 4. 2. 5. 3. 2. 6.]
[ 3.  1.  5.  3.  7.  3.  9.  5.  3. 11.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [89]:
# Author: Alan G Isaac

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

## 이건 진짜 모르겠다.......

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [90]:
# Author: Nadav Horesh

w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [91]:
A= np.random.randint(0,3, (3,3,3))
A

array([[[2, 1, 1],
        [2, 2, 1],
        [2, 2, 1]],

       [[1, 0, 0],
        [1, 0, 2],
        [0, 2, 0]],

       [[1, 1, 0],
        [2, 2, 0],
        [2, 2, 0]]])

In [92]:
A.sum(axis=2) # 0 = -3, 1 =-2, 2=-1

array([[4, 5, 5],
       [1, 3, 2],
       [2, 4, 4]])

In [93]:
A = np.random.randint(0,5,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[26 23 33 20]
 [24 25 30 28]
 [31 27 34 33]]
[[26 23 33 20]
 [24 25 30 28]
 [31 27 34 33]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [94]:
# Author: Jaime Fernández del Río

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

#이해안되......

[0.61571697 0.38301234 0.47805012 0.54816736 0.44399242 0.64688651
 0.5229538  0.51957022 0.51762979 0.4266183 ]
0    0.615717
1    0.383012
2    0.478050
3    0.548167
4    0.443992
5    0.646887
6    0.522954
7    0.519570
8    0.517630
9    0.426618
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [95]:
# Author: Mathieu Blondel

# A = np.random.uniform(0,1,(5,5))
# B = np.random.uniform(0,1,(5,5))

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A)
print(B)
print("------")
print(A.T)
print(B.T)

# Slow version  
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
------
[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


array([19, 50])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [96]:
# Author: Warren Weckesser

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [97]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(B[:,:,None].shape) # None 을 해주면 뒤에 dimention 하나가 더 낌!
print(A * B[:,:,None])

(5, 5, 1)
[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [98]:
# Author: Eelco Hoogendoorn

A = np.arange(25).reshape(5,5)
print(A)
print('------------')
print(A[[0,1]])
print(A[[1,0]])
print('------------')
print(A[[0]])
print(A[[0,1]])
print(A[[0,2]]) # 행 number에 대해서만 가져옴
print('------------')
print(A[[0,1],[0,1]]) # 대각선으로 value를 가져옴.
print('------------')
A[[0,1]] = A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
------------
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[5 6 7 8 9]
 [0 1 2 3 4]]
------------
[[0 1 2 3 4]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]]
------------
[0 6]
------------
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [99]:
# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
print(faces.repeat(2,axis=1))
print("---------")
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
print(len(F)) # 10
print("---------")
F = F.reshape(len(F)*3,2) 
print("---------")
print(F)
F = np.sort(F,axis=1)
print("---------")
# print(F)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
print(G.dtype)
G = np.unique(G)
print(G)

[[75 75 76 76 90 90]
 [18 18 62 62 45 45]
 [65 65 52 52 28 28]
 [87 87 38 38 20 20]
 [97 97 51 51 59 59]
 [94 94 64 64 14 14]
 [97 97 52 52 44 44]
 [16 16 64 64 30 30]
 [82 82 10 10 45 45]
 [88 88 78 78 99 99]]
---------
10
---------
---------
[[75 76]
 [76 90]
 [90 75]
 [18 62]
 [62 45]
 [45 18]
 [65 52]
 [52 28]
 [28 65]
 [87 38]
 [38 20]
 [20 87]
 [97 51]
 [51 59]
 [59 97]
 [94 64]
 [64 14]
 [14 94]
 [97 52]
 [52 44]
 [44 97]
 [16 64]
 [64 30]
 [30 16]
 [82 10]
 [10 45]
 [45 82]
 [88 78]
 [78 99]
 [99 88]]
---------
[('p0', '<i8'), ('p1', '<i8')]
[(10, 45) (10, 82) (14, 64) (14, 94) (16, 30) (16, 64) (18, 45) (18, 62)
 (20, 38) (20, 87) (28, 52) (28, 65) (30, 64) (38, 87) (44, 52) (44, 97)
 (45, 62) (45, 82) (51, 59) (51, 97) (52, 65) (52, 97) (59, 97) (64, 94)
 (75, 76) (75, 90) (76, 90) (78, 88) (78, 99) (88, 99)]


![](https://ws3.sinaimg.cn/large/006tNc79gy1fzgb3tmxxvj30lp0lqac5.jpg)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [100]:
# Author: Jaime Fernández del Río

C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [101]:
# Author: Jaime Fernández del Río

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float) # sum of column
    # print(ret) # 각 원소들의 누적 합을 나타냄
    ret[n:] = ret[n:] - ret[:-n] # 중간만 남음.
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

In [102]:
# Author: Joe Kington / Erik Rigtorp
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
boolean 을 무효화하거나, 내부에서 float의 부호를 변경하는 방법

In [103]:
# Author: Nathaniel J. Smith

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z) # 반대로- 부호를 반대로 변경.
print(Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z) # 반대로- 부호를 반대로 변경.


[0 0 1 1 0 1 1 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 1 0 1 0 1 1 0 1 1 0 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 0 0 0 1 0 0 0 1 1 1 0 1 0 0 1 1 1 1 0 1 1 1 0 0 1 1 0 1
 1 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 1]


array([-0.53557796, -0.07201699,  0.92028015,  0.73041376,  0.6131672 ,
        0.3286724 ,  0.89537411, -0.21023356, -0.02412206, -0.23492202,
        0.13528881, -0.69540094,  0.09188189,  0.96919296, -0.7461363 ,
       -0.3124031 , -0.64600608, -0.90355139,  0.89817523,  0.52985627,
        0.87331311,  0.15668423, -0.72765829,  0.83675203,  0.05377609,
        0.74891378, -0.5457712 , -0.68284431,  0.91341812,  0.02711851,
        0.52117791, -0.90494756, -0.88778526, -0.227868  , -0.94697479,
        0.31027731, -0.79570144,  0.13081005,  0.52837073, -0.88165593,
       -0.3684361 ,  0.87017683, -0.74084971, -0.40276059, -0.20985375,
       -0.4647498 ,  0.49312192, -0.20097791, -0.62923836,  0.89177268,
        0.73897866, -0.68489162, -0.23669174, -0.06257562,  0.50341854,
        0.40984285, -0.74537233,  0.15666813,  0.87113949, -0.79397014,
        0.59323833, -0.65245507, -0.76354125,  0.02649851, -0.19692939,
       -0.05453491, -0.24964259, -0.71008344,  0.4357211 , -0.76

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [104]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 2.89646581  5.19697557  8.25818218  2.20831241 12.66437698  7.17559177
  2.1372673   9.0251711   5.9443973  10.05661638]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [105]:
# Author: Italmassov Kuanysh

# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.23409392 10.96961204  0.709175    2.73910996 10.05588709  5.30289731
   3.48755828  9.95277875  9.73037658  9.39203105]
 [ 5.83759709  4.84481132 13.24566746  1.95123141  6.15689694  8.99667752
   5.13585273  2.50244534  4.26678498  1.75788912]
 [ 3.07575054  5.72736819  1.74330742  2.68600094  4.55835015  5.67068293
   2.01953477  6.75957958 10.70035441 13.91631578]
 [ 2.61102352 10.70006076  0.24255126  2.56938098  9.94048711  4.34565709
   3.74004127  9.21039423  8.77751445  8.76841281]
 [ 4.65718816 13.49118225  0.41427526  5.32662772 12.66654245  5.32272276
   6.02856793 11.60526785  9.46589991  7.38837563]
 [ 0.43579737  0.2398677   9.84946868  6.98721465  0.91357317  6.25699019
   1.02783293  3.87604038  0.93229609  7.85194177]
 [ 8.63138712  0.86277124  1.31249836  9.31789725  2.06460396  4.45171195
   8.02001444  1.74945955 10.19262058 18.12908415]
 [ 8.1946502   0.04699008  1.75387623  8.53912508  1.3093563   4.97955332
   7.48407188  2.5929261  10.6426856  17.93824091]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [106]:
import numpy as np

In [107]:
# Author: Nicolas Rougier

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[1 9 6 4 3 4 8 3 8 7]
 [1 3 4 0 2 3 4 2 0 5]
 [8 7 8 8 4 6 3 4 5 1]
 [4 5 2 4 0 8 3 7 0 3]
 [5 5 8 2 1 9 3 1 2 8]
 [9 9 9 0 1 0 3 1 0 6]
 [3 5 5 1 4 9 4 0 7 7]
 [5 4 3 7 5 0 9 7 0 8]
 [7 7 4 1 5 0 2 3 7 7]
 [7 0 2 5 6 2 3 8 5 1]]
[[0 0 0 0 0]
 [0 1 9 6 4]
 [0 1 3 4 0]
 [0 8 7 8 8]
 [0 4 5 2 4]]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [108]:
from numpy.lib import stride_tricks

In [109]:
# Author: Stefan van der Walt

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,shape=(11,4),strides=(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [110]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition

In [111]:
# Author: Stefan van der Walt

Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [112]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [113]:
# Author: Chris Barker

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)
C.shape

[[[[4 1 3]
   [2 1 0]
   [2 3 0]]

  [[1 3 4]
   [1 0 0]
   [3 0 0]]

  [[3 4 1]
   [0 0 4]
   [0 0 3]]

  [[4 1 3]
   [0 4 0]
   [0 3 2]]

  [[1 3 4]
   [4 0 2]
   [3 2 2]]

  [[3 4 2]
   [0 2 3]
   [2 2 0]]

  [[4 2 4]
   [2 3 2]
   [2 0 3]]

  [[2 4 2]
   [3 2 1]
   [0 3 0]]]


 [[[2 1 0]
   [2 3 0]
   [0 3 0]]

  [[1 0 0]
   [3 0 0]
   [3 0 1]]

  [[0 0 4]
   [0 0 3]
   [0 1 1]]

  [[0 4 0]
   [0 3 2]
   [1 1 3]]

  [[4 0 2]
   [3 2 2]
   [1 3 4]]

  [[0 2 3]
   [2 2 0]
   [3 4 0]]

  [[2 3 2]
   [2 0 3]
   [4 0 3]]

  [[3 2 1]
   [0 3 0]
   [0 3 1]]]


 [[[2 3 0]
   [0 3 0]
   [2 0 0]]

  [[3 0 0]
   [3 0 1]
   [0 0 4]]

  [[0 0 3]
   [0 1 1]
   [0 4 1]]

  [[0 3 2]
   [1 1 3]
   [4 1 2]]

  [[3 2 2]
   [1 3 4]
   [1 2 0]]

  [[2 2 0]
   [3 4 0]
   [2 0 1]]

  [[2 0 3]
   [4 0 3]
   [0 1 2]]

  [[0 3 0]
   [0 3 1]
   [1 2 0]]]


 [[[0 3 0]
   [2 0 0]
   [2 1 0]]

  [[3 0 1]
   [0 0 4]
   [1 0 1]]

  [[0 1 1]
   [0 4 1]
   [0 1 4]]

  [[1 1 3]
   [4 1 2]
   [1 4 2]]

  [[1 3 4]
   

(8, 8, 3, 3)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

In [114]:
# Author: Eric O. Lebigot
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    print(Z)
    print('-----------')
    print(Z.T)
    print(np.diag(Z.diagonal()))
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

np.random.seed(7)
S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[4 9 6 3 3]
 [7 7 9 7 8]
 [9 8 7 6 4]
 [0 7 0 7 6]
 [3 5 8 8 7]]
-----------
[[4 7 9 0 3]
 [9 7 8 7 5]
 [6 9 7 0 8]
 [3 7 6 7 8]
 [3 8 4 6 7]]
[[4 0 0 0 0]
 [0 7 0 0 0]
 [0 0 7 0 0]
 [0 0 0 7 0]
 [0 0 0 0 7]]
[[ 4 16 15  3  6]
 [16  7 17 14 13]
 [15 17  7 42 12]
 [ 3 14 42  7 14]
 [ 6 13 12 14  7]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [115]:
# Author: Stefan van der Walt

p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [116]:
# Author: Robert Kern

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [117]:
# Author: Nicolas Rougier

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [118]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [119]:
# Author: Stefan Van der Walt

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

![](https://ws1.sinaimg.cn/large/006tNc79gy1fzhgehu8brj30vy0dkmz5.jpg)

In [120]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [121]:
# Author: Ryan G.

x = np.random.rand(57)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

4.25 µs ± 470 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
1.85 µs ± 373 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
2.38 µs ± 126 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [122]:
# Author: Gabe Schwartz

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[3 4]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [123]:
# Author: Robert Kern

Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 1 3]
 [1 2 4]
 [4 1 2]
 [1 3 0]
 [3 3 1]
 [1 2 4]
 [1 2 1]
 [1 4 1]
 [3 2 0]
 [4 3 0]]
[[4 1 3]
 [1 2 4]
 [4 1 2]
 [1 3 0]
 [3 3 1]
 [1 2 4]
 [1 2 1]
 [1 4 1]
 [3 2 0]
 [4 3 0]]
[[4 1 3]
 [1 2 4]
 [4 1 2]
 [1 3 0]
 [3 3 1]
 [1 2 4]
 [1 2 1]
 [1 4 1]
 [3 2 0]
 [4 3 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [124]:
# Author: Warren Weckesser

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [125]:
A = [1,2,3,3]
np.ascontiguousarray(A)

array([1, 2, 3, 3])

In [126]:
# Author: Jaime Fernández del Río

Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
[[0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [127]:
# Author: Alex Riley
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.random.randint(0,5,10)
B = np.random.randint(0,5,10)
print(A)
print(B)
print(np.einsum('i->', A))       # np.sum(A)
print(np.einsum('i,i->i', A, B)) # A * B
print(np.einsum('i,i', A, B))    # np.inner(A, B)
print(np.einsum('i,j->ij', A, B))    # np.outer(A, B)

[4 2 2 4 1 2 2 2 2 1]
[2 2 1 3 1 4 2 1 4 4]
22
[ 8  4  2 12  1  8  4  2  8  4]
53
[[ 8  8  4 12  4 16  8  4 16 16]
 [ 4  4  2  6  2  8  4  2  8  8]
 [ 4  4  2  6  2  8  4  2  8  8]
 [ 8  8  4 12  4 16  8  4 16 16]
 [ 2  2  1  3  1  4  2  1  4  4]
 [ 4  4  2  6  2  8  4  2  8  8]
 [ 4  4  2  6  2  8  4  2  8  8]
 [ 4  4  2  6  2  8  4  2  8  8]
 [ 4  4  2  6  2  8  4  2  8  8]
 [ 2  2  1  3  1  4  2  1  4  4]]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [128]:
# Author: Bas Swinckels

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [129]:
# Author: Evgeni Burovski

X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [130]:
# Author: Jessica B. Hamrick

X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.23945896  0.15085461]
