In [3]:
import numpy as np
import tensorflow as tf
print("PACKAGES LOADED")
print("CURRENT TF VERSION IS %s" % (tf.__version__))

PACKAGES LOADED
CURRENT TF VERSION IS 1.1.0


Computation Graph를 만드는 것이 중요한 턴서플로우
그걸 하는 Key가 Constants

In [6]:
sess = tf.Session()
print("OPEN SESSION")

OPEN SESSION


In [9]:
def print_tf(x):
    print("TYPE IS \n %s" % (type(x)))
    print("VALUE IS \n %s" % (x))
hello = tf.constant("HELLO. IT'S ME. ")
print_tf(hello)

TYPE IS 
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS 
 Tensor("Const_3:0", shape=(), dtype=string)


이상한 값이 나오는데, 이걸 알아보기 위해서는 언제나 sess.run()을 해야 한다.

In [11]:
hello_out = sess.run(hello)
print_tf(hello_out)

TYPE IS 
 <class 'bytes'>
VALUE IS 
 b"HELLO. IT'S ME. "


In [14]:
a = tf.constant(1.5)
b = tf.constant(2.5)
print_tf(a)
print_tf(b)

TYPE IS 
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS 
 Tensor("Const_6:0", shape=(), dtype=float32)
TYPE IS 
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS 
 Tensor("Const_7:0", shape=(), dtype=float32)


In [15]:
a_out = sess.run(a)
b_out = sess.run(b)
print_tf(a_out)
print_tf(b_out)

TYPE IS 
 <class 'numpy.float32'>
VALUE IS 
 1.5
TYPE IS 
 <class 'numpy.float32'>
VALUE IS 
 2.5


In [16]:
a_plus_b = tf.add(a,b)
print_tf(a_plus_b)

TYPE IS 
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS 
 Tensor("Add:0", shape=(), dtype=float32)


In [17]:
a_plus_b_out = sess.run(a_plus_b)
print_tf(a_plus_b_out)

TYPE IS 
 <class 'numpy.float32'>
VALUE IS 
 4.0


Computation Graph를 만들어야 한다.

## VARIABLES

In [18]:
weight = tf.Variable(tf.random_normal([5,2], stddev=0.1))
print_tf(weight)

TYPE IS 
 <class 'tensorflow.python.ops.variables.Variable'>
VALUE IS 
 <tf.Variable 'Variable:0' shape=(5, 2) dtype=float32_ref>


## GET VALUES?

In [19]:
weight_out = sess.run(weight)
print_tf(weight_out)

FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[Node: _send_Variable_0 = _Send[T=DT_FLOAT, client_terminated=true, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=3839819637940934136, tensor_name="Variable:0", _device="/job:localhost/replica:0/task:0/cpu:0"](Variable)]]

## ONCE INITALIZED

In [22]:
init = tf.global_variables_initializer()
sess.run(init)
print("INITIALZING ALL VARIABLES")

INITIALZING ALL VARIABLES


In [23]:
weight_out = sess.run(weight)
print_tf(weight_out)

TYPE IS 
 <class 'numpy.ndarray'>
VALUE IS 
 [[-0.02793471 -0.09574875]
 [-0.11508322  0.12553279]
 [-0.01724367 -0.03240476]
 [-0.02977209 -0.09083974]
 [ 0.04046966  0.06471991]]


## PLACEHOLDERS

In [24]:
x = tf.placeholder(tf.float32, [None, 5])
# 10 x5 가 될수도 20 x5 가 될 수 있다.
print_tf(x)

TYPE IS 
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS 
 Tensor("Placeholder:0", shape=(?, 5), dtype=float32)


## OPERATOPN WITH VARIABLES AND PLACEHOLDERS

In [27]:
oper = tf.matmul(x, weight)
# weight 5 x 2 와 ? , 5 
print_tf(oper)

TYPE IS 
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS 
 Tensor("MatMul_1:0", shape=(?, 2), dtype=float32)


In [30]:
data = np.random.rand(1,5)
oper_out = sess.run(oper, feed_dict={x: data})
print_tf(oper_out)

TYPE IS 
 <class 'numpy.ndarray'>
VALUE IS 
 [[-0.13431522  0.04206785]]


In [31]:
data = np.random.rand(10,5)
oper_out = sess.run(oper, feed_dict={x: data})
print_tf(oper_out) 

TYPE IS 
 <class 'numpy.ndarray'>
VALUE IS 
 [[-0.07611375  0.11040521]
 [-0.01392598 -0.05593339]
 [-0.12082792  0.03159451]
 [-0.04392831  0.02482421]
 [-0.05032933 -0.10810164]
 [-0.08453561  0.03970528]
 [-0.09870449  0.10426402]
 [-0.02090828 -0.06192812]
 [-0.11932024  0.00368203]
 [-0.12060579 -0.05056425]]
